package edu.tamu.wumrwds.database.mapper;

import edu.tamu.wumrwds.database.entity.ArticleToCategory;
import java.util.List;

public interface ArticleToCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_article_to_category
     *
     * @mbg.generated
     */
    ArticleToCategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_article_to_category
     *
     * @mbg.generated
     */
    List<ArticleToCategory> selectAll();
}