package edu.tamu.wumrwds.database.mapper;

import edu.tamu.wumrwds.database.entity.Article;
import java.util.List;

public interface ArticleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_article
     *
     * @mbg.generated
     */
    Article selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_article
     *
     * @mbg.generated
     */
    List<Article> selectAll();
}