package edu.tamu.wumrwds.database.mapper;

import edu.tamu.wumrwds.database.entity.Articletocategory;
import java.util.List;

public interface ArticletocategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_article_to_category
     *
     * @mbg.generated
     */
    Articletocategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_article_to_category
     *
     * @mbg.generated
     */
    List<Articletocategory> selectAll();
}