package edu.tamu.wumrwds.database.mapper;

import edu.tamu.wumrwds.database.entity.Article;
import edu.tamu.wumrwds.database.entity.ext.ArticleExt;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface ArticleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_article
     *
     * @mbg.generated
     */
    Article selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_article
     *
     * @mbg.generated
     */
    List<Article> selectAll();


    /**
     * Selects articles by given conditions.
     *
     * @param username
     * @param categoryId
     * @return
     */
    List<ArticleExt> selectArticles(String username, Integer categoryId);

    /**
     * Selects article ID by title.
     *
     * @param title
     * @return
     */
    List<Article> selectIdByTitle(String title);

    /**
     * Inserts a given record.
     *
     * @param record
     * @return
     */
    int insert(Article record);

    /**
     * Selects the most commented article.
     *
     * @return
     */
    Long selectMostCommented();

    /**
     * Deletes article by id.
     *
     * @param id
     * @return
     */
    int delete(Long id);
}