package edu.tamu.wumrwds.database.mapper;

import edu.tamu.wumrwds.database.entity.Category;
import java.util.List;

public interface CategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_category
     *
     * @mbg.generated
     */
    Category selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_category
     *
     * @mbg.generated
     */
    List<Category> selectAll();
}