package edu.tamu.wumrwds.database.mapper;

import edu.tamu.wumrwds.database.entity.Category;
import edu.tamu.wumrwds.database.entity.dto.CategoryDTO;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface CategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_category
     *
     * @mbg.generated
     */
    Category selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_category
     *
     * @mbg.generated
     */
    List<Category> selectAll();

    List<CategoryDTO> selectAvgCommentCount();
}