package edu.tamu.wumrwds.database.mapper;

import edu.tamu.wumrwds.database.entity.User;
import edu.tamu.wumrwds.database.entity.ext.UserExt;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_user
     *
     * @mbg.generated
     */
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_user
     *
     * @mbg.generated
     */
    List<User> selectAll();

    List<UserExt> selectUsers(String username, Integer roleId);
}