package edu.tamu.wumrwds.database.mapper;

import edu.tamu.wumrwds.database.entity.User;
import java.util.List;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_user
     *
     * @mbg.generated
     */
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_user
     *
     * @mbg.generated
     */
    List<User> selectAll();
}